'use client';
import Link from 'next/link';
import { usePathname, useRouter } from 'next/navigation';
import { useState, useEffect, useRef, type FormEvent, type ReactNode } from 'react';
import { api, json, money, type Movie, type Episode, type Category, type User } from '../../lib/platform';
import { useSession } from './context';
import { useResource, Failure, Skeleton } from './catalog';
import { Brand } from '../Brand';
import { Icon, type IconName } from '../Icon';
import { ProcessingJobs } from './processing-jobs';

const sections: [string, string, IconName][] = [['','Тойм','grid'],['movies','Кинонууд','film'],['categories','Ангиллууд','bookmark'],['translation','Орчуулгын студи','language'],['jobs','Боловсруулалтын ажлууд','history'],['settings','Тохиргоо','settings']];
export function AdminShell({ children }: { children: ReactNode }) {
  const path = usePathname();
  const [open, setOpen] = useState(false); const toggle = useRef<HTMLButtonElement>(null);
  useEffect(() => setOpen(false), [path]);
  useEffect(() => { const close = (e: KeyboardEvent) => { if (open && e.key === 'Escape') { setOpen(false); toggle.current?.focus(); } }; document.addEventListener('keydown', close); return () => document.removeEventListener('keydown', close); }, [open]);
  return <div className="admin-layout"><aside className={`admin-sidebar${open ? ' open' : ''}`}>
    <div className="admin-brand-row"><Brand href="/admin"/><button ref={toggle} className="admin-menu-toggle icon-button" aria-label="Админ цэс" aria-expanded={open} aria-controls="admin-nav" onClick={() => setOpen(!open)}><Icon name={open ? 'x' : 'menu'}/></button></div><small>УДИРДЛАГЫН ХЭСЭГ</small>
    <nav id="admin-nav" aria-label="Админ цэс">{sections.map(([slug, title, icon]) => { const active = slug ? path.startsWith(`/admin/${slug}`) : path === '/admin'; return <Link aria-current={active ? 'page' : undefined} className={active ? 'active' : ''} href={`/admin${slug ? '/' + slug : ''}`} key={slug}><Icon name={icon}/>{title}</Link>; })}<span className="nav-group-label">БҮРТГЭЛ</span>{[['episodes','Бүх анги'],['payments','Төлбөр'],['users','Хэрэглэгчид']].map(([slug,title]) => <Link className={path.startsWith(`/admin/${slug}`) ? 'active' : ''} key={slug} href={`/admin/${slug}`}>{title}</Link>)}</nav><Link className="return-site" href="/"><Icon name="left"/> Вебсайт руу буцах</Link></aside><main className="admin-content">{children}</main></div>;
}
function Heading({ title, children }: { title: string; children?: ReactNode }) { return <div className="admin-heading"><div><span className="eyebrow">shortkinomn / УДИРДЛАГА</span><h1>{title}</h1></div>{children}</div>; }
export function Dashboard() {
  const { data, error, reload } = useResource<Record<'movies' | 'users' | 'episodes' | 'revenue', { total: number }>>('/admin/dashboard');
  return <><Heading title="Ерөнхий тойм"><Link className="button" href="/admin/movies/new">＋ Шинэ кино</Link></Heading>{error ? <Failure error={error} retry={reload}/> : !data ? <Skeleton/> : <><div className="admin-grid">{[['movies','Кино'],['episodes','Анги'],['users','Хэрэглэгч'],['revenue','Баталгаажсан орлого']].map(([key, label]) => <div className="panel stat" key={key}><span>{label}</span><strong>{key === 'revenue' ? money(data.revenue.total) : data[key as keyof typeof data].total}</strong></div>)}</div><section className="panel admin-section"><h2>Шинэ түүх нийтлэх</h2><p className="admin-note">Кино үүсгэх → Анги нэмэх → Видео оруулах → Орчуулгыг хянах → Урьдчилан үзэх → Нийтлэх</p><Link className="button secondary" href="/admin/movies">Кино удирдах →</Link></section></>}</>;
}
function MovieList() {
  const { data, error, reload } = useResource<Movie[]>('/admin/movies');
  return <><Heading title="Кино"><Link className="button" href="/admin/movies/new">＋ Шинэ кино</Link></Heading>{error ? <Failure error={error} retry={reload}/> : !data ? <Skeleton/> : <div className="admin-table-wrap"><table><thead><tr><th>Кино</th><th>Төлөв</th><th>Анги</th><th>Үнэ</th><th/></tr></thead><tbody>{data.map(m => <tr key={m.id}><td><Link href={`/admin/movies/${m.id}`}>{m.title_mn}</Link></td><td data-label="Төлөв">{m.status}</td><td data-label="Анги">{m.episode_count} / {m.total_episodes}</td><td data-label="Үнэ">{money(m.price)}</td><td><Link href={`/admin/movies/${m.id}`}>Засах →</Link></td></tr>)}</tbody></table>{!data.length && <div className="admin-empty">Эхний киногоо нэмээрэй.</div>}</div>}</>;
}
const defaults = { title_mn: '', title_original: '', slug: '', description: '', poster_url: '', backdrop_url: '', trailer_url: '', country: '', year: new Date().getFullYear(), price: 0, total_episodes: 0, status: 'DRAFT', featured: false, trending: false, new_release: true, category_ids: [] as string[], genre_ids: [] as string[] };
function MovieForm({ movie }: { movie?: Movie }) {
  const [draft, setDraft] = useState(movie ? { ...defaults, ...movie, featured: !!movie.featured, trending: !!movie.trending, new_release: !!movie.new_release, category_ids: movie.categories.map(c => c.id), genre_ids: movie.genres.map(c => c.id) } : defaults);
  const { data: categories } = useResource<Category[]>('/admin/categories'), { data: genres } = useResource<Category[]>('/admin/genres');
  const [busy, setBusy] = useState(false), [error, setError] = useState(''); const router = useRouter(); const { toast } = useSession();
  async function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); if(movie?.status==='PUBLISHED'&&draft.status!=='PUBLISHED'&&!window.confirm('Киног нийтлэгдсэн жагсаалтаас буулгах уу?'))return; setBusy(true); setError(''); try { const saved = await api<Movie>(`/admin/movies${movie ? '/' + movie.id : ''}`, json(movie ? 'PUT' : 'POST', draft)); toast('Кино хадгалагдлаа.'); router.push(`/admin/movies/${saved.id}`); router.refresh(); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  const fields: [keyof typeof defaults, string][] = [['title_mn','Монгол нэр'],['title_original','Эх нэр'],['slug','URL нэр (slug)'],['country','Улс'],['poster_url','Poster URL'],['backdrop_url','Backdrop URL'],['trailer_url','Trailer URL']];
  return <form className="panel admin-form" onSubmit={submit}>{fields.map(([key, label]) => <label key={key}>{label}<input required={key === 'title_mn' || key === 'slug'} type={key.endsWith('_url') ? 'url' : 'text'} value={String(draft[key])} onChange={e => setDraft({ ...draft, [key]: e.target.value })}/></label>)}<label>Төлөв<select value={draft.status} onChange={e => setDraft({ ...draft, status: e.target.value })}>{['DRAFT','PROCESSING','PUBLISHED','ARCHIVED'].map(s => <option key={s}>{s}</option>)}</select></label><label className="wide">Тайлбар<textarea value={draft.description} onChange={e => setDraft({ ...draft, description: e.target.value })}/></label>{([['year','Он'],['price','Үнэ (₮)'],['total_episodes','Төлөвлөсөн нийт анги']] as const).map(([key, label]) => <label key={key}>{label}<input required type="number" min={key === 'year' ? 1900 : 0} value={draft[key]} onChange={e => setDraft({ ...draft, [key]: Number(e.target.value) })}/></label>)}<div className="wide checkbox-row">{([['featured','Онцлох'],['trending','Редакцын сонголт'],['new_release','Шинэ']] as const).map(([key, label]) => <label key={key}><input type="checkbox" checked={draft[key]} onChange={e => setDraft({ ...draft, [key]: e.target.checked })}/>{label}</label>)}</div>{([['category_ids','Ангилал',categories],['genre_ids','Төрөл',genres]] as const).map(([key, label, items]) => <fieldset className="wide" key={key}><legend>{label}</legend><div className="checkbox-row">{items?.map(c => <label key={c.id}><input type="checkbox" checked={draft[key].includes(c.id)} onChange={e => setDraft({ ...draft, [key]: e.target.checked ? [...draft[key], c.id] : draft[key].filter(id => id !== c.id) })}/>{c.name}</label>)}{items?.length === 0 && <Link href="/admin/categories">Ангилал / төрөл нэмэх →</Link>}</div></fieldset>)}{error && <p className="form-error wide" role="alert">{error}</p>}<div className="form-actions"><button className="button" disabled={busy}>{busy ? 'Хадгалж байна…' : 'Кино хадгалах'}</button>{movie && <Link className="button secondary" href={`/movies/${movie.slug}`}>Public хуудас ↗</Link>}</div></form>;
}
function EpisodeEditor({ episode, reload }: { episode: Episode; reload: () => void }) {
  const [editing, setEditing] = useState(false), [title, setTitle] = useState(episode.title), [number, setNumber] = useState(episode.episode_number), [free, setFree] = useState(!!episode.is_free), [busy, setBusy] = useState(false); const { toast } = useSession();
  async function save() { setBusy(true); try { await api(`/admin/episodes/${episode.id}`, json('PATCH', { title, episode_number: number, is_free: free })); setEditing(false); reload(); toast('Анги хадгалагдлаа.'); } catch (e) { toast((e as Error).message); } finally { setBusy(false); } }
  return <tr><td>{editing ? <input aria-label="Анги" type="number" min={1} value={number} onChange={e => setNumber(Number(e.target.value))}/> : String(episode.episode_number).padStart(2, '0')}</td><td>{editing ? <input aria-label="Ангийн нэр" value={title} onChange={e => setTitle(e.target.value)}/> : episode.title}</td><td data-label="Төлөв">{episode.status}</td><td>{editing ? <label><input aria-label="Үнэгүй" type="checkbox" checked={free} onChange={e => setFree(e.target.checked)}/>Үнэгүй</label> : episode.is_free ? 'Үнэгүй' : 'Premium'}</td><td><Link href={`/admin/translation?episode=${episode.id}`}>Боловсруулах →</Link></td><td><button disabled={busy} onClick={() => editing ? void save() : setEditing(true)}>{editing ? 'Хадгалах' : 'Засах'}</button>{episode.status === 'PUBLISHED' && <button disabled={busy} onClick={async () => { if(!window.confirm('Энэ ангийг нийтлэгдсэн жагсаалтаас буулгах уу?'))return; try { await api(`/admin/episodes/${episode.id}`, { method: 'DELETE' }); reload(); toast('Анги public жагсаалтаас буулаа.'); } catch (e) { toast((e as Error).message); } }}>Нийтлэл буулгах</button>}</td></tr>;
}
export function EpisodeTable({ episodes, reload }: { episodes: Episode[]; reload: () => void }) { return <div className="admin-table-wrap"><table><thead><tr><th>№</th><th>Нэр</th><th>Төлөв</th><th>Эрх</th><th>Studio</th><th/></tr></thead><tbody>{episodes.map(e => <EpisodeEditor episode={e} reload={reload} key={e.id}/>)}</tbody></table>{!episodes.length && <div className="admin-empty">Анги нэмэгдээгүй байна.</div>}</div>; }
function EpisodeUploader({ movieId, episodes, reload }: { movieId: string; episodes: Episode[]; reload: () => void }) {
  const next = Math.max(0, ...episodes.map(e => e.episode_number)) + 1;
  const [number, setNumber] = useState(next), [title, setTitle] = useState(''), [free, setFree] = useState(next <= 5), [busy, setBusy] = useState(false); const router = useRouter(); const { toast } = useSession();
  async function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); setBusy(true); try { const result = await api<{ id: string }>('/admin/episodes', json('POST', { movie_id: movieId, episode_number: number, title: title || `${number}-р анги`, is_free: free })); reload(); router.push(`/admin/translation?episode=${result.id}`); } catch (e) { toast((e as Error).message); } finally { setBusy(false); } }
  return <section className="panel admin-section"><h2>＋ Анги нэмэх</h2><form className="episode-form" onSubmit={submit}><label>Дугаар<input type="number" min={1} max={10000} value={number} onChange={e => { const n = Number(e.target.value); setNumber(n); setFree(n <= 5); }}/></label><label>Ангийн нэр<input value={title} onChange={e => setTitle(e.target.value)} placeholder={`${number}-р анги`}/></label><label className="checkbox-row"><input type="checkbox" checked={free} onChange={e => setFree(e.target.checked)}/>Үнэгүй</label><button className="button" disabled={busy}>{busy ? 'Үүсгэж байна…' : 'Видео оруулах →'}</button></form></section>;
}
function MovieEditor({ id }: { id: string }) {
  const { data, error, reload } = useResource<{ movie: Movie; episodes: Episode[] }>(id === 'new' ? null : `/admin/movies/${id}`);
  const { toast } = useSession(); const router = useRouter();
  if (id === 'new') return <><Heading title="Шинэ кино"/><MovieForm/></>;
  if (error) return <Failure error={error} retry={reload}/>;
  if (!data) return <Skeleton/>;
  return <><Heading title={data.movie.title_mn}><button className="button secondary" onClick={async () => { if(!window.confirm('Киног архивлах уу? Нийтэд харагдахгүй болно.'))return; try { await api(`/admin/movies/${id}`, { method: 'DELETE' }); toast('Кино архивлагдлаа.'); router.push('/admin/movies'); } catch (e) { toast((e as Error).message); } }}>Архивлах</button></Heading><MovieForm key={data.movie.id} movie={data.movie}/><section className="admin-section"><h2>Ангиуд</h2><EpisodeTable episodes={data.episodes} reload={reload}/></section><EpisodeUploader key={data.episodes.length} movieId={id} episodes={data.episodes} reload={reload}/></>;
}
function Episodes() { const { data, error, reload } = useResource<Episode[]>('/admin/episodes'); return <><Heading title="Бүх анги"/>{error ? <Failure error={error} retry={reload}/> : !data ? <Skeleton/> : <EpisodeTable episodes={data} reload={reload}/>}</>; }
function Taxonomy({ type, title }: { type: 'categories' | 'genres'; title: string }) {
  const { data, error, reload } = useResource<Category[]>(`/admin/${type}`); const { toast } = useSession(); const [busy, setBusy] = useState(false);
  async function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const form = e.currentTarget; setBusy(true); try { await api(`/admin/${type}`, json('POST', Object.fromEntries(new FormData(form)))); form.reset(); reload(); toast('Нэмэгдлээ.'); } catch (e) { toast((e as Error).message); } finally { setBusy(false); } }
  return <section className="panel admin-section"><h2>{title}</h2><form className="inline-form" onSubmit={submit}><label>Нэр<input name="name" required maxLength={80}/></label><label>Slug<input name="slug" required pattern="[a-z0-9-]+" maxLength={100}/></label><button className="button" disabled={busy}>Нэмэх</button></form>{error && <Failure error={error} retry={reload}/>}<div className="category-chips">{data?.map(c => <button aria-label={`${c.name} устгах`} key={c.id} onClick={async () => { if(!window.confirm(c.name+' ангиллыг устгах уу?'))return; try { await api(`/admin/${type}/${c.id}`, { method: 'DELETE' }); reload(); } catch (e) { toast((e as Error).message); } }}>{c.name} ×</button>)}</div></section>;
}
interface AdminPayment { id: string; email: string; title_mn: string; amount: number; status: string; transaction_id: string | null; purchase_id: string }
function PaymentVerify({ payment, reload }: { payment: AdminPayment; reload: () => void }) {
  const [reference, setReference] = useState(''), [checked, setChecked] = useState(false), [busy, setBusy] = useState(false); const { toast } = useSession();
  return <article className="panel admin-section"><h3>{payment.title_mn} · {money(payment.amount)}</h3><p>{payment.email} · <span className="status-label">{payment.status}</span></p><p className="admin-note">Хүсэлт: {payment.purchase_id}</p>{payment.status === 'PENDING' ? <form className="inline-form" onSubmit={async e => { e.preventDefault(); setBusy(true); try { await api(`/admin/payments/${payment.id}/verify`, json('POST', { transactionId: reference })); toast('Төлбөр баталгаажиж, эрх нээгдлээ.'); reload(); } catch (e) { toast((e as Error).message); } finally { setBusy(false); } }}><label>Банкны гүйлгээний давтагдашгүй дугаар<input required minLength={3} maxLength={160} value={reference} onChange={e => setReference(e.target.value)}/></label><label className="checkbox-row"><input required type="checkbox" checked={checked} onChange={e => setChecked(e.target.checked)}/>Хүлээн авсан дүн, валют, хүсэлтийг шалгасан</label><button className="button" disabled={busy || !checked}>Баталгаажуулах</button></form> : <p className="admin-note">Гүйлгээ: {payment.transaction_id}</p>}</article>;
}
function Payments() { const { data, error, reload } = useResource<AdminPayment[]>('/admin/payments'); return <><Heading title="Төлбөр"/><p className="admin-note">Банкны орлогыг шалгасны дараа баталгаажуулна. Баталгаажуулсан админ болон гүйлгээний дугаар хадгалагдана.</p>{error ? <Failure error={error} retry={reload}/> : !data ? <Skeleton/> : data.length ? data.map(p => <PaymentVerify key={p.id} payment={p} reload={reload}/>) : <p className="admin-empty">Төлбөрийн хүсэлт алга.</p>}</>; }
function Users() { const { data, error, reload } = useResource<User[]>('/admin/users'); return <><Heading title="Хэрэглэгчид"/>{error ? <Failure error={error} retry={reload}/> : !data ? <Skeleton/> : <div className="admin-table-wrap"><table><thead><tr><th>Нэр</th><th>И-мэйл</th><th>Эрх</th></tr></thead><tbody>{data.map(u => <tr key={u.id}><td>{u.name}</td><td>{u.email}</td><td>{u.role}</td></tr>)}</tbody></table></div>}</>; }
function Settings() { const { data, error, reload } = useResource<{ paymentProvider: string; paymentEnabled: boolean; paymentInstructions: string; storage: string; freeEpisodesDefault: number }>('/admin/settings'); return <><Heading title="Тохиргоо"/>{error ? <Failure error={error} retry={reload}/> : !data ? <Skeleton/> : <section className="panel"><h2>Платформын тохиргоо</h2><p>Үнэгүй анги: эхний {data.freeEpisodesDefault} (анги бүрээр өөрчилж болно)</p><p>Storage: {data.storage}</p><p>Төлбөр: {data.paymentProvider} · {data.paymentEnabled ? 'Нээлттэй' : 'Тохируулаагүй'}</p><p className="admin-note">Төлбөрийн зааврыг серверийн PAYMENT_INSTRUCTIONS хувьсагчаар тохируулна. Нууц түлхүүрүүд зөвхөн сервер дээр хадгалагдана.</p></section>}</>; }
export function AdminPage() { const route = usePathname().split('/').filter(Boolean).slice(1); if (!route.length) return <Dashboard/>; if (route[0] === 'movies') return route[1] ? <MovieEditor key={route[1]} id={route[1]}/> : <MovieList/>; if (route[0] === 'jobs') return <ProcessingJobs/>; if (route[0] === 'episodes') return <Episodes/>; if (route[0] === 'categories') return <><Heading title="Ангилал ба төрөл"/><Taxonomy type="categories" title="Ангилал"/><Taxonomy type="genres" title="Төрөл"/></>; if (route[0] === 'payments') return <Payments/>; if (route[0] === 'users') return <Users/>; if (route[0] === 'settings') return <Settings/>; return <Heading title="Хуудас олдсонгүй"/>; }
